name: Build APK with Buildozer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            zip unzip openjdk-17-jdk \
            libffi-dev libssl-dev \
            libsqlite3-dev libncurses5 \
            libncursesw5 libbz2-dev \
            libreadline-dev liblzma-dev \
            zlib1g-dev

      - name: Install Python & Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Make sure buildozer.spec exists
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Install Android SDK Build Tools
        run: |
          yes | sdkmanager "build-tools;34.0.0" "platform-tools" "platforms;android-34"

      - name: Accept Licenses
        run: yes | sdkmanager --licenses

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyKivyApp-APK
          path: bin/*.apk
