name: Build APK with Buildozer

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk \
            libffi-dev libssl-dev \
            libsqlite3-dev libbz2-dev \
            libreadline-dev liblzma-dev zlib1g-dev

      - name: Install Python tools
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Initialize Buildozer if missing
        run: |
          if [ ! -f buildozer.spec ]; then
            buildozer init
          fi

      - name: Install Android SDK + Accept Licenses
        run: |
          yes | sdkmanager "platform-tools" "platforms;android-34" "build-tools;34.0.0"
          yes | sdkmanager --licenses

      - name: Build APK
        run: |
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MyKivyApp-APK
          path: bin/*.apk
